# Build settings

markdown: redcarpet

highlighter: false# Site settings

title: "sellmaggots"

description: > # this means to ignore newlines until "email:"
   Yes,I prefer Appolo


email: casamila@qq.com
#blog logo
logo: "/assets/images/df_logo.jpg"

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"


name: sellmaggots 
author: 'Sellmaggots'
author_image: "/assets/images/author.jpg"

paginate:	5

<<<<<<< HEAD
url: "http://myblog.***.***" 
# the base hostname & protocol for your site baseurl: "."

=======
url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: .
>>>>>>> ef3f470078f80940835e61df8478570b2e15fdd7

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/sellmaggots
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
